refactor: better handling to killall

diff --git a/bin/xds3 b/bin/xds3
--- a/bin/xds3
+++ b/bin/xds3
@@ -150,66 +150,73 @@ blue_underlined() { print_in_color "\e[4;34m" "$*"; }
 magenta_underlined() { print_in_color "\e[4;35m" "$*"; }
 cyan_underlined() { print_in_color "\e[4;36m" "$*"; }
 
+get_battery_level() {
+  local event_id="$1"
+  local mac_address
+  local capacity
+
+  mac_address=$(
+    </proc/bus/input/devices awk -v handler="event${event_id}" \
+      '/H: Handlers=/{if ($0 ~ handler) print prev} {prev=$0}' \
+      | awk -F'=' '/U: Uniq=/{print $2}' | tr '[:upper:]' '[:lower:]'
+  )
+  capacity=$(cat "/sys/class/power_supply/sony_controller_battery_${mac_address}/capacity")
+
+  echo "Battery: $(green "${capacity}%")"
+}
+
+kill_current_instance() {
+  set +e # dont exit on error
+
+  if [[ -n "$(pgrep xboxdrv)" ]]; then
+    echo "Stopping current instance of $(blue "xboxdrv")..."
+    killall xboxdrv --wait
+    echo "Stopped $(blue "xboxdrv")"
+    echo
+  fi
+
+  set -e # exit on error again
+}
+
 xds3_start_command() {
   # shellcheck disable=SC2154
+
+  # args
   event_id=${args[event_id]}
   daemon=${args[--daemon]:=0}
 
-  get_battery_level() {
-  	local mac_address
-  	mac_address=$(
-  		</proc/bus/input/devices awk -v handler="event${event_id}" \
-  			'/H: Handlers=/{if ($0 ~ handler) print prev} {prev=$0}' |
-  			awk -F'=' '/U: Uniq=/{print $2}' | tr '[:upper:]' '[:lower:]'
-  	)
+  # Kill the current running xboxdrv
+  kill_current_instance
 
-  	echo "Battery: $(cat "/sys/class/power_supply/sony_controller_battery_${mac_address}/capacity")%"
-  }
+  # Build the xboxdrv command as an array
+  command=(
+    "--evdev" "/dev/input/event${event_id}"
+    "--evdev-keymap" "BTN_START=Start,BTN_MODE=Guide,BTN_SELECT=Back,BTN_SOUTH=A,BTN_EAST=B,BTN_WEST=X,BTN_NORTH=Y,BTN_TL=LB,BTN_TR=RB,BTN_TL2=LT,BTN_TR2=RT,BTN_THUMBL=TL,BTN_THUMBR=TR,BTN_DPAD_UP=DU,BTN_DPAD_DOWN=DD,BTN_DPAD_LEFT=DL,BTN_DPAD_RIGHT=DR"
+    "--evdev-absmap" "ABS_X=X1,ABS_Y=Y1,ABS_RX=X2,ABS_RY=Y2,ABS_Z=LT,ABS_RZ=RT"
+    "--axismap" "-Y1=Y1,-Y2=Y2"
+    "--calibration" "RT=0:127:255,LT=0:127:255"
+    "--mimic-xpad"
+    "--detach-kernel-driver"
+    "--quiet"
+    "--silent"
+  )
 
-  start_xboxdrv() {
-  	green "Starting xboxdrv for: /dev/input/event${event_id}"
+  # Add --daemon and --detach conditionally
+  if [[ $daemon -eq 1 ]]; then
+    command+=("--daemon")
+    command+=("--detach")
+  else
+    echo "Press Ctrl-C to quit."
+  fi
 
-  	# Kill active xboxdrv
-  	{
-  		set +e # dont exit on error
-  		killall xboxdrv --wait --interactive
-  		set -e
-  	} 2>&1
-
-  	# Show battery
-  	get_battery_level
-
-  	# Build the xboxdrv command as an array
-  	command=(
-  		"--evdev" "/dev/input/event${event_id}"
-  		"--evdev-keymap" "BTN_START=Start,BTN_MODE=Guide,BTN_SELECT=Back,BTN_SOUTH=A,BTN_EAST=B,BTN_WEST=X,BTN_NORTH=Y,BTN_TL=LB,BTN_TR=RB,BTN_TL2=LT,BTN_TR2=RT,BTN_THUMBL=TL,BTN_THUMBR=TR,BTN_DPAD_UP=DU,BTN_DPAD_DOWN=DD,BTN_DPAD_LEFT=DL,BTN_DPAD_RIGHT=DR"
-  		"--evdev-absmap" "ABS_X=X1,ABS_Y=Y1,ABS_RX=X2,ABS_RY=Y2,ABS_Z=LT,ABS_RZ=RT"
-  		"--axismap" "-Y1=Y1,-Y2=Y2"
-  		"--calibration" "RT=0:127:255,LT=0:127:255"
-  		"--mimic-xpad"
-  		"--detach-kernel-driver"
-  		"--quiet"
-  		"--silent"
-  	)
-
-  	# Add --daemon and --detach conditionally
-  	if [[ $daemon -eq 1 ]]; then
-  		command+=("--daemon")
-  		command+=("--detach")
-  	else
-  		echo "Press Ctrl-C to quit."
-  	fi
-
-  	xboxdrv "${command[@]}"
-  }
-
-  start_xboxdrv
+  green "Starting xboxdrv for: $(blue /dev/input/event"$event_id")"
+  get_battery_level "$event_id"
+  xboxdrv "${command[@]}"
 
 }
 
 xds3_stop_command() {
-  echo "$(green Parando todas as instâncias de xboxdrv)"
-  sudo killall xboxdrv
+  kill_current_instance
 
 }
 
